export const SIGNUP_SUCCESS = "SIGN_UP_SUCCESS";
export const LOGIN = "LOGIN";

export const CREATE_TABLE_RESULT = "CREATE_TABLE_RESULT";
export const SHOW_TABLE_RESULT = "SHOW_TABLE_RESULT";
export const NO_TABLE_RESULT = "NO_TABLE_RESULT";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";
export const SHOW_TASKS = "SHOW_TASKS";
export const SHOW_TASKS_SUCCESS = "SHOW_TASKS_SUCCESS";
export const SHOW_TASKS_ERROR = "SHOW_TASKS_ERROR";


